# Generated by Django 3.2 on 2023-07-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.CharField(max_length=1000, null=True, verbose_name='Описание'),
        ),
    ]
