# Generated by Django 3.2 on 2023-07-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_title_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Категоря'),
        ),
    ]
