# Generated by Django 3.2 on 2023-07-09 12:13

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_alter_comment_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, validators=[reviews.validators.validate_year], verbose_name='Дата выхода произведения'),
        ),
    ]
